/* types.inc
 * Type tags for the basic Scheme data types
 *
 * Programmer: Mayer Goldberg, 2010
 */

#define T_VOID 		937610
#define T_NIL 		722689
#define T_BOOL 		741553
#define T_CHAR 		181048
#define T_INTEGER 	945311
#define T_STRING 	799345
#define T_SYMBOL 	368031
#define T_PAIR 		885397
#define T_VECTOR 	335728
#define T_CLOSURE 	276405
#define T_UNDEFINED 451794
#define T_FRACTION  922870
#define T_BOX       864017
#define E_EMPTY     544512
#define E_EQ        183403
#define E_ZERO      183403
#define E_NOT       101555
#define E_CAR       957412
#define E_CDR       645713
#define E_CONS      110463
#define E_PLUS      358902
#define E_MINUS     511179
#define E_INTEGER   615181
#define E_INT_TO_BOOL 602995
#define E_PINTEGER  602995
#define E_PBOOLEAN  921183
#define E_PCHAR     685967
#define E_PCLOSURE  286949
#define E_PPAIR     743140
#define E_PSYMBOL   529751
#define E_PVECTOR   569917
#define E_PSTRING   510364
#define E_PNULL     183731
#define E_PLIST     805664
#define E_MAP       111363
#define E_CHAR_TO_INTEGER 248183
#define E_INTEGER_TO_CHAR 911091
#define E_LIST      400183
#define E_NUM_EQ    152305
#define E_GT        777096
#define E_LT        155936
#define E_CADR      721327
#define E_PRIVATE   775216
#define E_APPEND    722858
#define E_LENGTH    508854
#define E_APPLY     414227

/*
 *
 *
 *
 *  572874 294755 989204 646495 725032 234097
 */
